stages:
    - build
    - test

build pr1:
    stage: build
    image: gcc
    only:
        changes:
            - Pr1/
    artifacts:
        paths:
            - Pr1/Mytar
    script:
        - cd Pr1/Mytar
        - make

test pr1:
    stage: test
    image: gcc
    only:
        changes:
            - Pr1/
    script:
        - cd Pr1/Mytar
        - ./test.sh
