stages:
    - build
    - test
    - advanced

build pr1:
    stage: build
    image: gcc
    artifacts:
        paths:
            - Pr1/Mytar/mytar
    script:
        - cd Pr1/Mytar
        - make

test pr1:
    stage: test
    image: ubuntu 
    before_script:
        - apt-get update && apt-get --assume-yes install xxd file curl
    script:
        - cd Pr1/Mytar
        - ./test.sh

build pr2:
    stage: build
    image: ubuntu
    artifacts:
        paths:
            - Pr2/FUSE_myFS/fs-fuse
    before_script:
        - apt-get update && apt-get --assume-yes install build-essential pkg-config libfuse-dev
    script:
        - cd Pr2/FUSE_myFS
        - make

test pr2:
    stage: test
    image: gcc
    before_script:
        - apt-get update && apt-get --assume-yes install xxd file fuse
    script:
        - cd Pr2/FUSE_myFS
        - ./test1.sh -m || { teststatus=$?; true; }
        - ../my-fsck-static-64 virtual-disk
        - cat fuse.log
        - cat fuserr.log
        - xxd -l 16 virtual-disk
        - '[[ $teststatus -eq 0 ]]'

advanced pr2:
    stage: advanced
    image: gcc
    artifacts:
        paths:
            - Pr2/FUSE_myFS2/fs-fuse2
    before_script:
        - apt-get update && apt-get --assume-yes install build-essential pkg-config libfuse-dev xxd file fuse
    script:
        - cd Pr2/FUSE_myFS2
        - make test
        - cat fuse.log
        - cat fuserr.log
