stages:
    - build
    - test

build pr1:
    stage: build
    image: gcc
    artifacts:
        paths:
            - Pr1/Mytar/mytar
    script:
        - cd Pr1/Mytar
        - make

test pr1:
    stage: test
    image: ubuntu 
    before_script:
        - apt-get update && apt-get --assume-yes install xxd file curl
    script:
        - cd Pr1/Mytar
        - ./test.sh
