stages:
    - build
    - test

build pr1:
    stage: build
    image: gcc
    artifacts:
        paths:
            - Pr1/Mytar/mytar
    script:
        - cd Pr1/Mytar
        - make

test pr1:
    stage: test
    image: ubuntu 
    before_script:
        - apt-get update && apt-get --assume-yes install xxd file curl
    script:
        - cd Pr1/Mytar
        - ./test.sh

build pr2:
    stage: build
    image: gcc
    artifacts:
        paths:
            - Pr1/FUSE_myFS/fs-fuse
    script:
        - cd Pr2/FUSE_myFS
        - make

test pr2:
    stage: test
    image: gcc
    before_script:
        - apt-get update && apt-get --assume-yes install xxd file
    script:
        - cd Pr2/FUSE_myFS
        - ./test1.sh
        - ../my-fsck-static-64 virtual-disk
        - cat fuse.log
        - cat fuserr.log
        - xxd virtual-disk | head
